openapi: "3.0.0"
info:
  title: Tshirt Store API
  description: course to create ecomm API
  version: 1.1.0
  contact:
    email: denilbhatt@mail.com
    url: "https://truts.dev"
# servers:
#   - url: "https:/localhost:4000/api/v1"
#     description: For localhost - secure
#   - url: "https:/localhost:4000/api/v1"
#     description: For localhost - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: For localhost
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - String
      summary: Returns a greet message from api
      responses:
        200:
          description: All good and success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: Internal server error
